doc(frontend) : added Frontend documentation
Motouom/PackIt pull request #38
Opened 2024-07-19 09:55 UTC by Arielpetit

2024-07-19 12:44 UTC, Motouom requested changes
The name of the application is PackIt and not Packit. please change it everywhere in your documentation.

2024-07-19 12:52 UTC, Motouom requested changes

2024-07-19 12:52 UTC, Motouom commented on doc/Frontend-Documentation.md
> +## Functionality of the Project
Functionalities instead of functionality

2024-07-19 12:52 UTC, Motouom commented on doc/Frontend-Documentation.md
> +Packit offers a straightforward process for shortening long URLs. Users simply paste their lengthy URLs into the application, and with a single click, Packit generates a shortened link. This shortene
into the application, and with a single  when you use a "and", no need to put a comma before

2024-07-19 12:52 UTC, Motouom commented on doc/Frontend-Documentation.md
> +## Technologies Used
Please endeavor to precise the versions of the technologies that are being used

2024-07-22 14:48 UTC, Calebasah approved these changes

2024-07-23 07:33 UTC, Motouom approved these changes
Nice work, the front-end images, app logo and other diagrams that have to be included.

2024-07-23 08:11 UTC, mbunwe-victor approved these changes
Good job

2024-07-23 08:17 UTC, merged